# Generated by Django 3.2.25 on 2024-06-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='owner',
        ),
    ]
