# Generated by Django 3.2.25 on 2024-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_rename_user_address_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='owner',
            new_name='user',
        ),
    ]
