# Generated by Django 3.2.25 on 2024-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20240614_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
