# Generated by Django 3.2.25 on 2024-06-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240621_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
    ]
